sudo: false
language: python
cache: pip
python:
  - "3.6"
env:
  - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/master"
addons:
  apt:
    packages:
    - lftp
deploy:
  skip_cleanup: true # don't remove stuff we've built
  provider: script
  script: curl https://raw.githubusercontent.com/OpenDataServices/opendataservices-deploy/master/open-contracting-extension_registry-deploy.sh | bash -
  on:
    all_branches: true
install:
  - curl -s -S $BASEDIR/tests/install.sh | bash -
script:
  - curl -s -S $BASEDIR/tests/script.sh | bash -
  - python compile.py
  - mkdir build; mv extensions.* build
